import type { Partner } from "@/lib/types";

export const PARTNERS: Partner[] = [
  {
    id: "maya-chen",
    name: "Maya Chen",
    role: "Backend engineer",
    location: "Austin",
    blurb: "Ships APIs quickly and wants a design partner for the interface.",
    canTeach: ["Node.js", "MongoDB", "TypeScript", "Docker"],
    wantsToLearn: ["React", "UI/UX", "Figma"],
    domains: ["FinTech", "EdTech"],
  },
  {
    id: "jordan-hale",
    name: "Jordan Hale",
    role: "ML builder",
    location: "Toronto",
    blurb: "Prototypes agents in Python and is looking for a frontend co-builder.",
    canTeach: ["Python", "AI Agents", "SQL"],
    wantsToLearn: ["React", "Next.js", "UI/UX"],
    domains: ["HealthTech", "EdTech"],
  },
  {
    id: "priya-nair",
    name: "Priya Nair",
    role: "Product designer",
    location: "London",
    blurb: "Owns the visual system and wants to learn how the data layer fits together.",
    canTeach: ["Figma", "UI/UX", "React"],
    wantsToLearn: ["Node.js", "GraphQL", "MongoDB"],
    domains: ["Creator Economy", "Social"],
  },
  {
    id: "leo-vargas",
    name: "Leo Vargas",
    role: "Systems developer",
    location: "Mexico City",
    blurb: "Comfortable with infrastructure and curious about agent workflows.",
    canTeach: ["Go", "Docker", "System Design", "SQL"],
    wantsToLearn: ["AI Agents", "TypeScript", "Next.js"],
    domains: ["DevTools", "Gaming"],
  },
  {
    id: "aisha-rahman",
    name: "Aisha Rahman",
    role: "Mobile designer-dev",
    location: "Singapore",
    blurb: "Ships polished mobile UI and wants a pair who can teach applied ML.",
    canTeach: ["Swift", "UI/UX", "Figma"],
    wantsToLearn: ["Python", "AI Agents", "SQL"],
    domains: ["HealthTech", "Gaming"],
  },
  {
    id: "noah-kim",
    name: "Noah Kim",
    role: "Full-stack intern",
    location: "Seoul",
    blurb: "Strong on the web stack and looking for someone to push architecture.",
    canTeach: ["Next.js", "GraphQL", "TypeScript", "React"],
    wantsToLearn: ["MongoDB", "System Design", "Docker"],
    domains: ["FinTech", "Climate"],
  },
];
